// <auto-generated />
using System;
using Infrastructure.Request.Database.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Request.Migrations
{
    [DbContext(typeof(RequestDataContext))]
    partial class RequestDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Request.Entities.Client.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Domain.Request.Entities.Request.RequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasMaxLength(80)
                        .HasColumnType("INTEGER")
                        .HasColumnName("ClientId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("Domain.Request.Entities.Request.RequestItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Name");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestItem", (string)null);
                });

            modelBuilder.Entity("Domain.Request.Entities.Client.ClientEntity", b =>
                {
                    b.OwnsOne("Domain.Request.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ClientEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("NVARCHAR")
                                .HasColumnName("Address_Number");

                            b1.Property<string>("Road")
                                .IsRequired()
                                .HasColumnType("NVARCHAR")
                                .HasColumnName("Address_Road");

                            b1.HasKey("ClientEntityId");

                            b1.ToTable("Client");

                            b1.WithOwner()
                                .HasForeignKey("ClientEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Request.Entities.Request.RequestItemEntity", b =>
                {
                    b.HasOne("Domain.Request.Entities.Request.RequestEntity", "RequestEntity")
                        .WithMany("RequestItensEntities")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Request.ValueObjects.PriceItem", "PriceItem", b1 =>
                        {
                            b1.Property<int>("RequestItemEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Price")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("RequestItemEntityId");

                            b1.ToTable("RequestItem");

                            b1.WithOwner()
                                .HasForeignKey("RequestItemEntityId");
                        });

                    b.OwnsOne("Domain.Request.ValueObjects.QuantityItem", "QuantityItem", b1 =>
                        {
                            b1.Property<int>("RequestItemEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuantityItem");

                            b1.HasKey("RequestItemEntityId");

                            b1.ToTable("RequestItem");

                            b1.WithOwner()
                                .HasForeignKey("RequestItemEntityId");
                        });

                    b.Navigation("PriceItem")
                        .IsRequired();

                    b.Navigation("QuantityItem")
                        .IsRequired();

                    b.Navigation("RequestEntity");
                });

            modelBuilder.Entity("Domain.Request.Entities.Request.RequestEntity", b =>
                {
                    b.Navigation("RequestItensEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
