// <auto-generated />
using System;
using Infrastructure.Stock.Database.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Stock.Migrations
{
    [DbContext(typeof(ItemDataContext))]
    [Migration("20240722170445_FirstCommit")]
    partial class FirstCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Stock.Entities.Item.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Domain.Stock.Entities.Item.ItemEntity", b =>
                {
                    b.OwnsOne("Domain.Stock.ValueObjects.PriceItem", "PriceItem", b1 =>
                        {
                            b1.Property<int>("ItemEntityId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Price")
                                .HasColumnType("DECIMAL(18,2)")
                                .HasColumnName("PriceItem");

                            b1.HasKey("ItemEntityId");

                            b1.ToTable("Item");

                            b1.WithOwner()
                                .HasForeignKey("ItemEntityId");
                        });

                    b.OwnsOne("Domain.Stock.ValueObjects.QuantityItem", "QuantityItemStock", b1 =>
                        {
                            b1.Property<int>("ItemEntityId")
                                .HasColumnType("int");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuantityItem");

                            b1.HasKey("ItemEntityId");

                            b1.ToTable("Item");

                            b1.WithOwner()
                                .HasForeignKey("ItemEntityId");
                        });

                    b.Navigation("PriceItem")
                        .IsRequired();

                    b.Navigation("QuantityItemStock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
